### ISSUE TITLE
framework compilation error

### ISSUE THREAD

**Issue by ilopez85** [BurgerZ/jBART#152]
```
[30.03.2016 15:15:23] I: **** Compiling framework-ext-res.apk ****
[30.03.2016 15:15:23] I: Searching for available XML patches...
[30.03.2016 15:15:23] I: Using aapt: /home/ivan/jBART-master/data/tools/nix/aapt_miui_v7
[30.03.2016 15:15:23] I: I: Using Apktool 2.1.0-285da3-SNAPSHOT
[30.03.2016 15:15:24] W: W: Could not find sources
[30.03.2016 15:15:24] I: I: Building resources...
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/attrs.xml:11: error: Attribute "paintColor" has already been defined
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:11: error: Error declaring public resource attr/paintColor for included package miui
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:230: error: Error declaring public resource xml/miui_manifest for included package miui
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:346: error: Error declaring public resource string/select_all for included package miui
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:562: error: Error declaring public resource id/icon for included package miui
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:566: error: Error declaring public resource id/cancel for included package miui
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:581: error: Error declaring public resource style/Animation for included package miui
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:23: error: Public entry identifier 0x11010014 entry index is larger than available symbols (index 20, total symbols 20).
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:23: error: Public symbol attr/arrowRedUpBmp declared here is not defined.
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:578: error: Public entry identifier 0x110b0031 entry index is larger than available symbols (index 49, total symbols 49).
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:578: error: Public symbol id/volume_divider declared here is not defined.
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:579: error: Public entry identifier 0x110b0032 entry index is larger than available symbols (index 50, total symbols 49).
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:579: error: Public symbol id/volume_headset declared here is not defined.
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:585: error: Public entry identifier 0x110c0005 entry index is larger than available symbols (index 5, total symbols 5).
[30.03.2016 15:15:24] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res/values/public.xml:585: error: Public symbol style/KeyboardButtonNormal declared here is not defined.
[30.03.2016 15:15:24] W: Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, p, --rename-manifest-package, com.miui.rom, --version-code, 1010000, --version-name, 1.1.0.0, -F, /tmp/APKTOOL8234057568655554600.tmp, -x, -0, arsc, -0, arsc, -I, /home/ivan/jBART-master/data/frameworks/1.apk, -I, /home/ivan/jBART-master/data/frameworks/16.apk, -S, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res, -M, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/AndroidManifest.xml]
[30.03.2016 15:15:24] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
[30.03.2016 15:15:24] W: 	at brut.androlib.Androlib.buildResources(Androlib.java:371)
[30.03.2016 15:15:24] W: 	at brut.androlib.Androlib.build(Androlib.java:281)
[30.03.2016 15:15:24] W: 	at brut.androlib.Androlib.build(Androlib.java:254)
[30.03.2016 15:15:24] W: 	at brut.apktool.Main.cmdBuild(Main.java:224)
[30.03.2016 15:15:24] W: 	at brut.apktool.Main.main(Main.java:84)
[30.03.2016 15:15:24] W: Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, p, --rename-manifest-package, com.miui.rom, --version-code, 1010000, --version-name, 1.1.0.0, -F, /tmp/APKTOOL8234057568655554600.tmp, -x, -0, arsc, -0, arsc, -I, /home/ivan/jBART-master/data/frameworks/1.apk, -I, /home/ivan/jBART-master/data/frameworks/16.apk, -S, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res, -M, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/AndroidManifest.xml]
[30.03.2016 15:15:24] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
[30.03.2016 15:15:24] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
[30.03.2016 15:15:24] W: 	... 5 more
[30.03.2016 15:15:24] W: Caused by: brut.common.BrutException: could not exec (exit code = 1): [/home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, p, --rename-manifest-package, com.miui.rom, --version-code, 1010000, --version-name, 1.1.0.0, -F, /tmp/APKTOOL8234057568655554600.tmp, -x, -0, arsc, -0, arsc, -I, /home/ivan/jBART-master/data/frameworks/1.apk, -I, /home/ivan/jBART-master/data/frameworks/16.apk, -S, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/res, -M, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk/AndroidManifest.xml]
[30.03.2016 15:15:24] W: 	at brut.util.OS.exec(OS.java:95)
[30.03.2016 15:15:24] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:424)
[30.03.2016 15:15:24] W: 	... 6 more
[30.03.2016 15:15:24] S: pro.burgerz.bart.core.exceptions.CompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [java, -Xms1774m, -Xmx1774m, -jar, /home/ivan/jBART-master/data/tools/lib/apktool-2.1.0-285da3-SNAPSHOT-BZ.jar, b, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-ext-res.apk, -f, -a, /home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, -c, -p, /home/ivan/jBART-master/data/frameworks, -o, /home/ivan/jBART-master/china-to-global.zip.bzprj/appCompiled/system/framework/framework-ext-res.apk]
[30.03.2016 15:15:24] I: **** Compiling framework-res.apk ****
[30.03.2016 15:15:24] I: Searching for available XML patches...
[30.03.2016 15:15:24] I: Using aapt: /home/ivan/jBART-master/data/tools/nix/aapt_miui_v7
[30.03.2016 15:15:24] I: I: Using Apktool 2.1.0-285da3-SNAPSHOT
[30.03.2016 15:15:25] W: W: Could not find sources
[30.03.2016 15:15:25] I: I: Building resources...
[30.03.2016 15:15:28] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res/values-mcc214-mnc4/arrays.xml:4: error: Resource entry config_operatorConsideredNonRoaming already has bag item ^index_0.
[30.03.2016 15:15:28] W: W: /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res/values-mcc214-mnc04/arrays.xml:4: Originally defined here.
[30.03.2016 15:15:28] I: I: aapt: warning: string 'global_action_reboot_summary' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'keyguard_password_pin_failed' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: zh_CN
[30.03.2016 15:15:28] I: I: aapt: warning: string 'keyguard_password_puk_failed' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: zh_CN
[30.03.2016 15:15:28] I: I: aapt: warning: string 'media_info_audio_not_supported' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'media_info_video_not_supported' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'reboot_title' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'storage_external_usb' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'storage_ic_usb1' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'storage_ic_usb2' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] I: I: aapt: warning: string 'storage_phone' has no default translation in /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res; found: es
[30.03.2016 15:15:28] W: Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, p, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 19, --version-name, 4.4.4-V7.2.4.0.KHCCNDA, -F, /tmp/APKTOOL6893493498322671192.tmp, -x, -0, arsc, -0, arsc, -S, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res, -M, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/AndroidManifest.xml]
[30.03.2016 15:15:28] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
[30.03.2016 15:15:28] W: 	at brut.androlib.Androlib.buildResources(Androlib.java:371)
[30.03.2016 15:15:28] W: 	at brut.androlib.Androlib.build(Androlib.java:281)
[30.03.2016 15:15:28] W: 	at brut.androlib.Androlib.build(Androlib.java:254)
[30.03.2016 15:15:28] W: 	at brut.apktool.Main.cmdBuild(Main.java:224)
[30.03.2016 15:15:28] W: 	at brut.apktool.Main.main(Main.java:84)
[30.03.2016 15:15:28] W: Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, p, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 19, --version-name, 4.4.4-V7.2.4.0.KHCCNDA, -F, /tmp/APKTOOL6893493498322671192.tmp, -x, -0, arsc, -0, arsc, -S, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res, -M, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/AndroidManifest.xml]
[30.03.2016 15:15:28] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
[30.03.2016 15:15:28] W: 	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
[30.03.2016 15:15:28] W: 	... 5 more
[30.03.2016 15:15:28] W: Caused by: brut.common.BrutException: could not exec (exit code = 1): [/home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, p, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 19, --version-name, 4.4.4-V7.2.4.0.KHCCNDA, -F, /tmp/APKTOOL6893493498322671192.tmp, -x, -0, arsc, -0, arsc, -S, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/res, -M, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk/AndroidManifest.xml]
[30.03.2016 15:15:28] W: 	at brut.util.OS.exec(OS.java:95)
[30.03.2016 15:15:28] W: 	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:424)
[30.03.2016 15:15:28] W: 	... 6 more
[30.03.2016 15:15:28] S: pro.burgerz.bart.core.exceptions.CompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [java, -Xms1774m, -Xmx1774m, -jar, /home/ivan/jBART-master/data/tools/lib/apktool-2.1.0-285da3-SNAPSHOT-BZ.jar, b, /home/ivan/jBART-master/china-to-global.zip.bzprj/appDecompiled/system__framework/framework-res.apk, -f, -a, /home/ivan/jBART-master/data/tools/nix/aapt_miui_v7, -c, -p, /home/ivan/jBART-master/data/frameworks, -o, /home/ivan/jBART-master/china-to-global.zip.bzprj/appCompiled/system/framework/framework-res.apk]
```

**Comment by BurgerZ** [comment]
Try to rename or delete file /home/ivan/jBART-master/data/tools/nix/aapt_miui_v7
Anyway, I don not accept any issues about MIUI.
