### ISSUE TITLE
Error compilation Android 6.0 MIUI 8 ( REDMIPRO )

### ISSUE THREAD

**Issue by Fays** [BurgerZ/jBART#168]
Decompile
java -jar /home/fayz/0_HMPro_BETA/Bin-HMPro/apktool-3.0.9-BZ.jar d -t HMPro MiuiHome.apk 
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (com.miui.home.launcher.assistant), pkgId: 27
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fayz/apktool/framework/1-HMPro.apk
I: Loading resource table from file: /home/fayz/apktool/framework/16-HMPro.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Package: com.miui.home (com.miui.home)
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Recompile via aapt_miui_v8
java -jar /home/fayz/0_HMPro_BETA/Bin-HMPro/apktool-2.1.0-BZ.jar b -a /home/fayz/0_HMPro_BETA/Bin-HMPro/aapt_miui_v8 MiuiHome
I: Using Apktool 2.1.0-285da3-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: Asset package include '/home/fayz/apktool/framework/1-HMPro.apk' not found.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/home/fayz/0_HMPro_BETA/Bin-HMPro/aapt_miui_v8, p, --version-code, 10000, --version-name, 1.0, -F, /tmp/APKTOOL333540431009005838.tmp, -0, arsc, -0, arsc, -I, /home/fayz/apktool/framework/1-HMPro.apk, -I, /home/fayz/apktool/framework/16-HMPro.apk, -S, /home/fayz/Téléchargements/MiuiHome/res, -M, /home/fayz/Téléchargements/MiuiHome/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/home/fayz/0_HMPro_BETA/Bin-HMPro/aapt_miui_v8, p, --version-code, 10000, --version-name, 1.0, -F, /tmp/APKTOOL333540431009005838.tmp, -0, arsc, -0, arsc, -I, /home/fayz/apktool/framework/1-HMPro.apk, -I, /home/fayz/apktool/framework/16-HMPro.apk, -S, /home/fayz/Téléchargements/MiuiHome/res, -M, /home/fayz/Téléchargements/MiuiHome/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/home/fayz/0_HMPro_BETA/Bin-HMPro/aapt_miui_v8, p, --version-code, 10000, --version-name, 1.0, -F, /tmp/APKTOOL333540431009005838.tmp, -0, arsc, -0, arsc, -I, /home/fayz/apktool/framework/1-HMPro.apk, -I, /home/fayz/apktool/framework/16-HMPro.apk, -S, /home/fayz/Téléchargements/MiuiHome/res, -M, /home/fayz/Téléchargements/MiuiHome/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:424)
	... 6 more

Recompile no aapt 
java -jar /home/fayz/0_HMPro_BETA/Bin-HMPro/apktool-2.1.0-BZ.jar b MiuiHome
I: Using Apktool 2.1.0-285da3-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: /home/fayz/Téléchargements/MiuiHome/res/layout/launcher.xml:6: error: Error: No resource found that matches the given name (at 'layout' with value '@com.miui.home.launcher.assistant:layout/screenview_assistant').
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5562351471087790666.tmp, p, --version-code, 10000, --version-name, 1.0, -F, /tmp/APKTOOL6347874250052873677.tmp, -0, arsc, -0, arsc, -I, /home/fayz/apktool/framework/1-HMPro.apk, -I, /home/fayz/apktool/framework/16-HMPro.apk, -S, /home/fayz/Téléchargements/MiuiHome/res, -M, /home/fayz/Téléchargements/MiuiHome/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5562351471087790666.tmp, p, --version-code, 10000, --version-name, 1.0, -F, /tmp/APKTOOL6347874250052873677.tmp, -0, arsc, -0, arsc, -I, /home/fayz/apktool/framework/1-HMPro.apk, -I, /home/fayz/apktool/framework/16-HMPro.apk, -S, /home/fayz/Téléchargements/MiuiHome/res, -M, /home/fayz/Téléchargements/MiuiHome/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5562351471087790666.tmp, p, --version-code, 10000, --version-name, 1.0, -F, /tmp/APKTOOL6347874250052873677.tmp, -0, arsc, -0, arsc, -I, /home/fayz/apktool/framework/1-HMPro.apk, -I, /home/fayz/apktool/framework/16-HMPro.apk, -S, /home/fayz/Téléchargements/MiuiHome/res, -M, /home/fayz/Téléchargements/MiuiHome/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:424)
	... 6 more

**Comment by BurgerZ** [comment]
Sorry, I do not accept any MIUI-related issues with apktool.
