### ISSUE TITLE
can't decompile settings.apk from Sharp Aquos S2

### ISSUE THREAD

**Issue by kkffiirr** [BurgerZ/jBART#211]
when trying to decompile the settings app, i get this message:
```
[16.05.2018 09:14:12] I: **** Decompiling Settings.apk ****
[16.05.2018 09:14:12] I: Using apktool_2.3.3.jar
[16.05.2018 09:14:13] I: I: Using Apktool 2.3.3 on Settings.apk
[16.05.2018 09:14:13] I: I: Loading resource table...
[16.05.2018 09:14:13] W: Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2792
[16.05.2018 09:14:13] W: 	at java.lang.String.substring(Unknown Source)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:171)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:360)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
[16.05.2018 09:14:13] W: 	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
[16.05.2018 09:14:13] W: 	at brut.androlib.Androlib.getResTable(Androlib.java:68)
[16.05.2018 09:14:13] W: 	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
[16.05.2018 09:14:13] W: 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
[16.05.2018 09:14:13] W: 	at brut.apktool.Main.cmdDecode(Main.java:164)
[16.05.2018 09:14:13] W: 	at brut.apktool.Main.main(Main.java:73)
[16.05.2018 09:14:13] E: pro.burgerz.bart.core.exceptions.DecompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [java, -Xmx3621m, -jar, C:\Intel\temp\adb\jBART-master\data\tools\lib\apktool_2.3.3.jar, d, -s, -f, -p, C:\Intel\temp\adb\jBART-master\data\frameworks, -o,
```

as you can see i tried to use the latest apktool, but no help.

**Comment by BurgerZ** [comment]
Try to use another Apktool version.
